channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
# to add
#conda install -c bioconda samtools
#conda install -c bioconda pysam
#conda install -c bioconda bedtools
#conda install matplotlib
